name: flutter_application_1
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  drift: ^2.4.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.5
  sqlite3_flutter_libs: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  drift_dev: ^2.4.1


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
